sonar.organization=cybersapienseci
sonar.projectKey=cybersapienseci_matching-service
sonar.projectName=AlphaECI Matching Service

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
